openapi: 3.1.0
info:
  title: Student Management System
  version: 1.0.0
servers:
  - url: https://localhost:8081/api
paths:
  /students:
    get:
      operationId: getAllStudents
      summary: Get all students
      responses:
        "200":
          description: Get all students successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllStudentsResponse'
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      operationId: addNewStudent
      summary: Add new student
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        "200":
          description: Add new student successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddNewStudentResponse'
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
    put:
      operationId: updateStudent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        "200":
          description: Update student
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateStudentResponse'
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /students/{id}:
    get:
      operationId: getStudentById
      summary: Get a student by Id
      parameters:
        - name: id
          in: path
          description: Student Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Get student information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStudentByIdResponse'
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
    delete:
      operationId: deleteStudentById
      summary: Delete a student by Id
      parameters:
        - name: id
          in: path
          description: Student Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Delete student information successfully
          content:
            application/json:
              schema:
                $ref: './components/schemas/response.yml#/Response'
              example:
                success: true
                message: Student deleted!
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        code:
          type: string
          example: 1234
        name:
          type: string
          example: Khanh
    GetAllStudentsResponse:
      type: object
      allOf:
        - $ref: './components/schemas/response.yml#/Response'
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Student'
    GetStudentByIdResponse:
      type: object
      allOf:
        - $ref: './components/schemas/response.yml#/Response'
      properties:
        data:
          $ref: '#/components/schemas/Student'
    AddNewStudentResponse:
      type: object
      allOf:
        - $ref: './components/schemas/response.yml#/Response'
      properties:
        data:
          $ref: '#/components/schemas/Student'
    UpdateStudentResponse:
      type: object
      allOf:
        - $ref: './components/schemas/response.yml#/Response'
      properties:
        data:
          $ref: '#/components/schemas/Student'
  responses:
    BadRequest:
      $ref: "./components/responses/400.yml"
    InternalServerError:
      $ref: "./components/responses/500.yml"
        