openapi: 3.0.3
info:
  title: Student Management System
  version: 1.0.0
servers:
  - url: https://localhost:8081/api
paths:
  /students:
    get:
      operationId: getAllStudents
      summary: Get all students
      responses:
        "200":
          description: Get all students successfully
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/GetAllStudentsResponse'
              example: 
                success: true
                data:
                  - id: 1
                    code: "001"
                    name: "Khanh"
                  - id: 2
                    code: "002"
                    name: "Quan"
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /students/{id}:
    get:
      operationId: getStudentById
      summary: Get a student by Id
      parameters:
        - name: id
          in: path
          description: Student Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Get student information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStudentByIdResponse'
              example:
                success: true
                data:
                  id: 1
                  code: "001"
                  name: Khanh
    delete:
      operationId: deleteStudentById
      summary: Delete a student by Id
      parameters:
        - name: id
          in: path
          description: Student Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Delete student information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example: 
                success: true
                messsage: Student deleted!
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        name:
          type: string
    GetAllStudentsResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Student'
    GetStudentByIdResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
      properties:
        data:
          type: object
          $ref: '#/components/schemas/Student'      
    Response:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        message:
          type: string
    InternalServerError:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
    BadRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
        